version: "3"
services:
  app:
    image: sebastianrp/umap-adonis-js:1.0.0
    volumes:
      - ./node:/var/www
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - back

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: umap
      MYSQL_USER: admin
      MYSQL_PASSWORD: cerealteam
      MYSQL_ROOT_PASSWORD: cerealteam1
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 4000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: cerealteam1
    networks:
      - back
networks:
  back:
